behaviors:
  MLHades:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 64
        learning_rate: 0.0003
      gail:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 64
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: MLHades/Assets/MLHades/Demos/
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    behavioral_cloning:
      demo_path: MLHades/Assets/MLHades/Demos/
      steps: 50000
      strength: 1.0
      samples_per_update: 0